#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 8          # 8 cores per GPU
#$ -l h_rt=09:00:0    # 240 hours runtime
#$ -l h_vmem=11G      # 11G RAM per core
#$ -l gpu=1        # request 1 GPU
#$ -l cluster=andrena  # Ensure that the job runs on Andrena nodes

module load anaconda3
conda activate nn_UNet
cd /data/home/acw676/nnUNetFrame/nnUNet/nnunetv2/dataset_conversion/

export nnUNet_raw="/data/scratch/acw676/nn_unet_data/dataset/nnUNet_raw/nnUNet_raw_data/"

python Dataset027_ACDC.py 
